### ISSUE TITLE
override returnSuccess/returnError statusCode

### ISSUE THREAD

**Issue by pinnareet** [thanakijwanavit/awsSchema#2]
now it can't be overridden

also would like a returnSuccess for a put operation that returns no body.

**Comment by thanakijwanavit** [comment]
do you mind giving example of the schema that doesnt have body?

**Comment by pinnareet** [comment]
> do you mind giving example of the schema that doesnt have body?

i can't find any exact examples aa, but it seems like it only has statusCode and headers. No body or any other content at all. 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT
